### ISSUE TITLE
iOS工程打不开

### ISSUE THREAD

**Issue by wangy0573** [taoweiji/cpp-android-ios-example#2]
提示下面三个错误：

/.../Cpp_IosAndroid/GitHub/cpp-android-ios-example/example/ios/example.xcodeproj:1:1 Unable to open base configuration reference file '/.../Cpp_IosAndroid/GitHub/cpp-android-ios-example/example/ios/Pods/Target Support Files/Pods-example/Pods-example.debug.xcconfig'.

Unable to load contents of file list: '/Target Support Files/Pods-example/Pods-example-frameworks-Debug-input-files.xcfilelist'

Unable to load contents of file list: '/Target Support Files/Pods-example/Pods-example-frameworks-Debug-output-files.xcfilelist'

**Comment by taoweiji** [comment]
如果是iOS也是同样打开example/ios项目，记得要先执行 pod install 哦。
